# Generated by Django 3.0.7 on 2020-06-16 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bartender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('glass', models.CharField(max_length=255)),
                ('instructions', models.CharField(max_length=255)),
                ('is_edited', models.BooleanField()),
                ('is_new', models.BooleanField()),
                ('image_url', models.CharField(max_length=1000, null=True)),
                ('bartender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tendersapi.Bartender')),
            ],
        ),
    ]
