# Generated by Django 3.0.7 on 2020-06-16 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tendersapi', '0002_auto_20200616_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=50)),
                ('measurement', models.CharField(max_length=50)),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tendersapi.Cocktail')),
            ],
        ),
    ]
