# Generated by Django 3.0.7 on 2020-06-21 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tendersapi', '0003_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bartender',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bartender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='external_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
