# Generated by Django 3.0.7 on 2020-06-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendersapi', '0004_auto_20200621_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
