# Generated by Django 3.0.7 on 2020-06-24 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tendersapi', '0005_auto_20200622_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='cocktail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tendersapi.Cocktail'),
        ),
    ]
