# Generated by Django 3.0.7 on 2020-06-25 16:13

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('tendersapi', '0006_auto_20200624_0336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cocktail',
            options={'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('date_added'), nulls_last=True),)},
        ),
    ]
